services:
  martin:
    env_file:
      - .env
    build: ./martin
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@martin-db/${POSTGRES_DB}
    depends_on:
      - martin-db
  martin-db:
    env_file:
      - .env
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data
